/*
 * This source file was generated by the Gradle 'init' task
 */
package mryazik.github.io;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javafx.scene.layout.BorderPane;

import mryazik.github.io.Classes.layoutLoad;


import java.util.logging.Level;
import java.util.logging.Logger;

public class App extends Application {
    public static Stage primaryStage;
    public static BorderPane rootLayout;

    public static Logger logger = Logger.getLogger(App.class.getName());

    public static void main(String[] args) {
        Application.launch();
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        App.primaryStage = primaryStage;

        showMainWindow();
    }

    private void showMainWindow()
    {
        try {
            FXMLLoader loader = new FXMLLoader(getClass().getResource("fxml/BorderPane.fxml"));

            rootLayout = loader.load();

            Scene scene = new Scene(rootLayout);
            primaryStage.setScene(scene);

            // загружаем главный VBox

            primaryStage.show();
        } catch (Exception e)
        {
            logger.log(Level.WARNING, "Не удалось загрузить BorderPane", e);
        }
    }
}
